### PR TITLE
Specify python version in run.py

### PR DESCRIPTION
**Pull request by benjamreis**
Prevent from using python3 by default

### CODE REVIEW

**Comment by benjamreis** [comment]
IDK why the CI failed.

**Comment by stormi** [comment]
> IDK why the CI failed.

Maybe @johnelse will know

**Comment by benjamreis** [comment]
Hmm weird indeed. Is there a `/usr/bin/python2` on the CI machine?
From my understanding all machine with Python2.7 package instaled has a `/usr/bin/python2` binary (which is a symbolic link on the python2.7 binary) but I might be wrong...

**Comment by stormi** [comment]
Previous commits on master from me also had the CI fail, so I don't think it's related to yours.

**Comment by johnelse** [comment]
travis is still using 16.04 so python3 isn't the default python yet.

Although

```
$ python --version
Python 3.6.7
```

looks like travis may be overriding that now, i.e. if you ask for python you get python3.

https://docs.travis-ci.com/user/languages/python/ suggests that that's the case.

**Pull request merged**
